myauth:
  eureka: #自定义用户密码，下面注册中心地址会用到
    username: xk
    password: xk123
eureka:
  client:
    registry-fetch-interval-seconds: 10 #默认30秒
    service-url:
      defaultZone: http://${myauth.eureka.username}:${myauth.eureka.password}@localhost:16001/eureka/ #注册中心地址
  instance:
    lease-renewal-interval-in-seconds: 10 #心跳时间
    lease-expiration-duration-in-seconds: 30 #发呆时间
    prefer-ip-address: true
security:
  user: #设置配置中心用户密码
    name: xk
    password: xk123
server:
  port: 16002 #服务端口配置
spring:
  application:
    name: config #配置中心应用名
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        git:
          clone-on-start: true
          uri: https://github.com/xukai0324/SpringCloud/
          search-paths: config
          username: xukai0324
          password: XK19930324
  rabbitmq:
    host: localhost
    port: 5672
    username: xk
    password: xk123
    virtual-host: /xk
logging:
  level: debug