myauth:
  eureka: #自定义用户密码，下面注册中心地址会用到
    username: xk
    password: xk123
eureka:
  client:
    service-url:
      defaultZone: http://${myauth.eureka.username}:${myauth.eureka.password}@localhost:16001/eureka/ #注册中心地址
spring:
  application:
    name: zuul
  cloud:
    config:
      name: ${spring.application.name}
      discovery:
        enabled: true
        serviceId: config
      fail-fast: true
      enabled: true
server:
  port: 16004
zuul:
  routes:
    api-platform:
      path: /platform/**
      serviceId: platform
  prefix:
  ignored-services: '*'
  strip-prefix: false